### ISSUE TITLE
Lemmy & (created)

### ISSUE THREAD

**Issue by silverpill** [vpzomtrrfrt/arewehs2019yet#1]
Lemmy doesn't send (created) and (expires) anymore:

- https://github.com/LemmyNet/lemmy/pull/2473
- https://docs.rs/http-signature-normalization-reqwest/latest/http_signature_normalization_reqwest/struct.Config.html#method.mastodon_compat

**Comment by vpzomtrrfrt** [comment]
Reflected in updated table
